version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: order_manager
      MYSQL_USER: order_manager
      MYSQL_PASSWORD: order_manager
    volumes:
      - ./db/mysql/mysql_ddl.sql:/docker-entrypoint-initdb.d/mysql_ddl.sql
