spring:
  application:
    name: "Order Manager"

  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/order_manager
    username: order_manager
    password: order_manager
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
graphql:
  servlet:
    exception-handlers-enabled: true